server.port=8080

camel.springboot.name=EipPatternsApplication
camel.springboot.main-run-controller=true

logging.level.com.alnafi.eip=INFO
logging.level.org.apache.camel=INFO
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
